notas/views.py
from urllib.parse import unquote
from flask import Blueprint, render_template, redirect, url_for, request
from otros.db import todas_las_notas, agregar_una_nota, buscar_una_nota_por_id, borrar_una_nota_por_id, actualizar_nota, comprobar_notas

notas_page = Blueprint('notas_page',__name__)

@notas_page.route('/notas')
def hola():
    notas = todas_las_notas()
    return render_template('hola.html', notas=notas)

@notas_page.route('/notas/crear', methods=['GET','POST'])
def notaNueva():
    if request.method == 'POST':
        agregar_una_nota(request.form['contenido'], request.form['titulo'])
        comprobar_notas()
        return redirect(url_for('notas_page.hola'))
    else:
        return render_template('notanueva.html')

@notas_page.route('/notas/editar/<int:notas_id>', methods=['GET','POST'])
def notaEditar(notas_id):
    nota = buscar_una_nota_por_id(notas_id)
    if request.method == 'POST':
        a,b=request.data.decode('utf-8').split('&contenido=')
        a = a[7:]
        actualizar_nota(notas_id, unquote(a), unquote(b))
        return redirect(url_for('notas_page.hola'))
    else:
        return render_template('notaeditar.html', nota=nota, notas_id=notas_id)

@notas_page.route('/notas/borrar/<int:notas_id>', methods=['GET','POST'])
def notaBorrar(notas_id):
    nota = buscar_una_nota_por_id(notas_id)
    if request.method == 'POST':
        borrar_una_nota_por_id(notas_id)
        return redirect(url_for('notas_page.hola'))
    else:
        return render_template('notaborrar.html', nota=nota)

notasimagenes/views.py
import os
from flask import Flask, Blueprint, render_template, request, redirect, url_for
from otros.db import agregar_nota_imagen, buscar_notas_imagenes_por_nota_id, buscar_una_nota_por_id, buscar_nota_imagen_por_id, borrar_una_nota_imagen_por_id
from constantes import UPLOAD_FOLDER

notas_imagenes_page = Blueprint('notas_imagenes_page',__name__)

@notas_imagenes_page.route("/notas/<int:nota_id>", methods=['GET','POST'])
def nota_imagen(nota_id):
    nota = buscar_una_nota_por_id(nota_id)
    dir = os.path.join(UPLOAD_FOLDER, str(nota_id))
    if os.path.isdir(dir):
        if request.method == 'POST':
            id = request.form['id']
            dir = os.path.join(UPLOAD_FOLDER, id)
            if id.isdigit() and os.path.exists(dir):
                file = request.files['file']
                agregar_nota_imagen(nota_id, file.filename, request.form['descripcion'])
                file.save(os.path.join(dir, file.filename))
                return redirect(url_for('notas_imagenes_page.nota_imagen', nota_id=nota_id))
            else:
                return "Hubo un problemas, lo siento."
        else:
            notas_imagen = buscar_notas_imagenes_por_nota_id(nota_id)
            aux = []
            for i in notas_imagen:
                dir = os.path.join('upload/', str(nota_id))
                dir = os.path.join(dir,i[2])
                aux.append([i[0],i[1],dir,i[3]])
            notas_imagen = aux;
            return render_template("nota_imagen.html",nota=nota, nota_id=nota_id, notas_imagen=notas_imagen)
    else:
        return "Esta nota no existe"

@notas_imagenes_page.route("/notas/<int:nota_id>/<int:nota_imagen_id>", methods=['GET','POST'])
def nota_imagen_perfil(nota_id, nota_imagen_id):
    if request.method == 'POST':
        fila = buscar_nota_imagen_por_id(nota_imagen_id)
        dir = os.path.join(UPLOAD_FOLDER, str(nota_id))
        dir = os.path.join(dir,fila[2])
        if os.path.exists(dir):
            borrar_una_nota_imagen_por_id(nota_imagen_id)
            os.remove(dir)
            return redirect(url_for('notas_imagenes_page.nota_imagen', nota_id=nota_id))
        else:
            return "El archivo buscado no existe"
    else:
        fila = buscar_nota_imagen_por_id(nota_imagen_id)
        if fila is None:
            return "No existe la nota-imagen buscada"
        else:
            dir = os.path.join('upload/', str(nota_id))
            dir = os.path.join(dir,fila[2])
            fila = [dir, fila[3], nota_id, nota_imagen_id]
            return render_template("nota_imagen_perfil.html", fila=fila)

templates/hola.html
{% extends "layout.html" %}
{% block style %}
    <link rel="stylesheet" href="{{url_for('static', filename='hola.css')}}">
{% endblock %}
{% block body %}
    <main class="contenedor-principal">
        <div class="">
            <h2>Ultimas notas creadas</h2>
            {% for nota in notas %}
                <div class="">
                    <div class="">
                        <ul class="list-group">
                            <li class="list-group-item">
                                <span>
                                    <img class="imagen-nota" src="{{url_for('static', filename='imagenes/file.jpeg')}}" width="25" height="25" alt="">
                                    <a class="titulo-nota" href="{{url_for('notas_page.notaEditar',notas_id=nota[0])}}">
                                        {{nota[1]}}
                                    </a>
                                </span>
                            </li>
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="titulo-chico">
            <h3>Buscar en las notas</h3>
            <form class="form-signin" action="" method="post">
                <input class="form-control" type="text" name="" placeholder="Buscar nota..">
                <input class="btn btn-primary separacion-chico" type="submit" value="Buscar">
            </form>
        </div>
    </main>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="{{url_for('static', filename='bootstrap/css/bootstrap.min.css')}}">
        {% block style %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-dark navbar-expand-md bg-dark">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="{{url_for('hola')}}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{{url_for('notas_page.hola')}}">Notas</a></li>
            </ul>
            <div class="">
                <span style="color: gray;"> Hola, Lucho!</span>
            </div>
        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

templates/nota_imagen.html
{% extends "layout.html" %}
{% block title %}
Subir archivos
{% endblock %}

{% block style %}
{% endblock %}

{% block body %}
    <h2>{{nota[1]}}</h2>
    <span style="white-space: pre-wrap">{{nota[2]}}</span>

    <h2>Subir un archivo</h2>
    <form class="" enctype="multipart/form-data" action="{{url_for('notas_imagenes_page.nota_imagen',nota_id=nota_id)}}" method="post">
        <input type="hidden" name="id" value="{{nota_id}}"><br>
        <input type="file" name="file"><br>
        <textarea type="text" name="descripcion" placeholder="Agregar comentario"></textarea><br>
        <input class="btn btn-primary" type="submit" name="" value="Subir">
    </form>

    {% for nota in notas_imagen %}
        <figure>
            <img src="{{url_for('static', filename=nota[2])}}" alt="">
            <figcaption><p>{{nota[3]}}</p></figcaption>
        </figure>
    {% endfor %}
{% endblock %}

templates/nota_imagen_perfil.html
{% extends "layout.html" %}
{% block title %}
Perfil de nota-imagen
{% endblock %}

{% block style %}
{% endblock %}

{% block body %}
    <h1>Hola</h1>
    <form action="{{url_for('notas_imagenes_page.nota_imagen_perfil', nota_id=fila[2], nota_imagen_id=fila[3])}}" method="post">
        <input class="btn btn-danger" type="submit" value="Borrar">
    </form>
    <figure>
        <img src="{{url_for('static', filename=fila[0])}}" alt="">
        <figcaption>{{fila[1]}}</figcaption>
    </figure>
{% endblock %}

templates/notaborrar.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Borrar nota</title>
    </head>
    <body>
        <nav>
            <a href="{{url_for('notas_page.hola')}}">Menu</a>
        </nav>
        <h1>Estas seguro que deseas borrar esta nota?</h1>
        <form class="" action="{{url_for('notas_page.notaBorrar',notas_id=nota[0])}}" method="delete">
            <input type="submit" value="Si">
        </form>
        <h2>{{nota[1]}}</h2>
        <p>{{nota[2]}}</p>
    </body>
</html>

templates/notaeditar.html
{% extends "layout.html" %}
{% block style %}
    <link rel="stylesheet" href="{{url_for('static', filename='notas/css/notas.css')}}">
{% endblock %}
{% block body %}
    <div id="sidebar-wrapper">
        <ul class="ul-editar">
          <li class="">
                <a href="{{url_for('notas_page.notaNueva')}}">
                    <input class="btn btn-success boton-editar" type="submit" value="">
                </a>
          </li>
          <li class="">
              <a href="{{url_for('notas_imagenes_page.nota_imagen', nota_id=notas_id)}}">
                  <input class="btn btn-primary boton-editar" type="submit" value="">
              </a>
          </li>
          <li class="">
              <input id="nota-borrar-btn" class="btn btn-danger boton-editar" type="submit" value="">
          </li>
        </ul>
    </div>

    <div class="contenedor-login">
        <div id="nota-editar">
            <h1 id="titulo-editar">Editar nota</h1>

            <div class="container-edit">
                <input id="titulo-nota" class="form-control" type="text" name="titulo" value="{{nota[1]}}">
                <textarea id="contenido-nota" class="form-control" name="contenido" rows="16" placeholder="Escribe aqui el contenido">{{nota[2]}}</textarea>
            </div>
        </div>

        <div id="nota-borrar">
            <h2>Borrar nota</h2>
            <p>No hay vuelta atrás.</p>
            <a id="a-notaBorrar" href=""></a>
            <input id="btn-notaBorrar" class="btn btn-danger" type="submit" value="Borrar">
        </div>
    </div>

    <script src="{{url_for('static', filename='jquery/jquery.min.js')}}"></script>
    <script src="{{url_for('static', filename='notas/js/notas.js')}}" type="text/javascript">
    </script>
     <script type="text/javascript">
         URL_BORRAR = "{{url_for('notas_page.notaBorrar', notas_id=notas_id)}}"
         URL_GUARDAR = "{{url_for('notas_page.notaEditar', notas_id=notas_id)}}"
         URL_HOLA = "{{url_for('notas_page.hola')}}"
         NOTA_ID = "{{notas_id}}"
     </script>
{% endblock %}

templates/notanueva.html
{% extends "layout.html" %}
{% block style %}
    <link rel="stylesheet" href="{{url_for('static', filename='hola.css')}}">
{% endblock %}
{% block body %}
    <div class="contenedor-login">
        <form class="form-signin" action="{{url_for('notas_page.notaNueva')}}" method="post">
            <h1 class="h2 font-weight-normal">Nota nueva</h1>
            <input class="form-control" type="text" name="titulo" placeholder="Titulo">
            <textarea class="form-control" name="contenido" rows="16" placeholder="Escribe aqui el contenido"></textarea>
            <button class="btn btn-primary" type="submit" name="button">Crear</button>
        </form>
    </div>
{% endblock %}